### PR TITLE
[REG-838] - Deploy unhashing to mainnet and polygon

### PR DESCRIPTION
**Pull request by DeRain**
### 1. Contracts versioning
- [ ] Make sure that the `patch` version of the contracts is increased if changes have been made to the `UNSRegistry`, `MintingManager` or `ProxyReader` contracts.
- [ ] Make sure that the `minor` version of the contracts is increased if breaking changes have been made to the `UNSRegistry`, `MintingManager` or `ProxyReader` contracts. It includes changes of interfaces.
### 2. Contracts licensing
- [ ] Make sure that no **SPDX-License-Identifier** defined in contracts.
- [ ] Make sure that the **header** is added to the new contract files. 
  ```
  // @author Unstoppable Domains, Inc.
  // @date {Month} {Day}(ordinal), {Year}
  ```
### 3. Coverage
- [ ] Make sure that the coverage of contracts has not decreased and strive **100%**
### 4. Configs versioning
- [x] Make sure that the version of `uns-config.json` is increased if changes have been made to the config.
- [ ] Make sure that the version of `resolver-keys.json` is increased if changes have been made to the config.
### 5. Package versioning
- [x] Make sure that the `patch` version of package is increased if valuable changes have been made to the package. It includes contracts update, configs update, etc.
- [ ] Make sure that the `major.minor` version of package is synced with version of `UNSRegistry` contract.
- [x] Make sure that the `CHANGELOG` is updated with short description for the new version. 
### 6. Code review
- [ ] `resolver-keys.json` code review is required from **DevTools** team
- [ ] For all other changes code review is required from **Registry** team

### CODE REVIEW

**Review by aquiladev — CHANGES_REQUESTED** [review]
- Why does Polygon contracts upgrade have 4 transactions instead of 3?
- Pls re-check `uns-config.json`, because implementation addresses for Mainnet and Polygon are identical, should not be like this

**Comment by DeRain** [comment]
> * Why does Polygon contracts upgrade have 4 transactions instead of 3?
> * Pls re-check `uns-config.json`, because implementation addresses for Mainnet and Polygon are identical, should not be like this

@aquiladev 
- https://polygonscan.com/address/0x7b29DaC7b5D3A90696c8B059CBF1FaE9af32FA28#code
- https://etherscan.io/address/0x7b29DaC7b5D3A90696c8B059CBF1FaE9af32FA28#code

**Comment by DeRain** [comment]
> * Why does Polygon contracts upgrade have 4 transactions instead of 3?
> * Pls re-check `uns-config.json`, because implementation addresses for Mainnet and Polygon are identical, should not be like this

@aquiladev 
4th transaction in polygon config is UnsOperator. I've deployed it by the accident. I could either transfer ownership on this contract or we abandon it.
https://polygonscan.com/address/0x4ff860525ccb6e992e0a4579860465f7ef581aed#code

**Comment by aquiladev** [comment]
ok, addresses looks good, I missed the case with deployment by an account with synced nonce.

regarding UNSOperator, I see that you deployed without proxy, I need to think how to convert in to upgradable or I'm gonna deploy another contracts (in the case we need to remove it from `.openzeppelin/polygon.json` in order to keep clean history)

**Review by aquiladev — APPROVED** [review]

**Review by bogdan — APPROVED** [review]

**Pull request merged**
